version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - ./deployment/build-s3-dist2.sh ${DIST_OUTPUT_BUCKET} ${SOLUTION_NAME} ${VERSION}
      - mkdir -p deployment/open-source/ && touch deployment/open-source/.empty
  post_build:
    commands:
      - aws s3 cp s3://solutions-build-assets/changelog-spec.yml buildspec.yml
artifacts:
  files:
    - .git/**/*
    - deployment/**/*
    - buildspec.yml
    - CHANGELOG.md
    - .cfnnag_*
